name: Build and Release Uno App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev dotnet-sdk-8.0

      - name: Display .NET version
        run: dotnet --info

      - name: Restore workloads
        run: dotnet workload restore Samples/UNO_Sample.Mobile/UNO_Sample.Mobile.csproj

      - name: Restore
        run: dotnet restore Samples/UNO_Sample.Mobile/UNO_Sample.Mobile.csproj

      - name: Publish
        run: |
          dotnet publish Samples/UNO_Sample.Mobile/UNO_Sample.Mobile.csproj \
          -c Release \
          -p:PublishSingleFile=true \
          -p:SelfContained=true \
          -o build_output

      - name: Zip output
        run: |
          cd build_output
          zip -r ../UNO_Sample.Mobile.zip .
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: UNO_Sample.Mobile.zip
          name: Release ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

