name: Build and Release Uno App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev dotnet-sdk-8.0

      - name: Display .NET version
        run: dotnet --info

      - name: Restore
        run: dotnet restore **/*.Skia.Gtk.csproj

      - name: Publish
        run: |
          dotnet publish **/*.Skia.Gtk.csproj \
            -c Release \
            -p:PublishSingleFile=true \
            -p:SelfContained=true \
            -o build_output

      - name: Zip output
        run: |
          cd build_output
          zip -r ../SprachsteuerungApp.zip .
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: SprachsteuerungApp.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}

